I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 358, in script
    if girl2_killed == False and girl2_geri == False:
  File "game/script.rpy", line 358, in <module>
    if girl2_killed == False and girl2_geri == False:
NameError: name 'girl2_geri' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 358, in script
    if girl2_killed == False and girl2_geri == False:
  File "/home/armen/prog/renpy-8.3.7-sdk/renpy/ast.py", line 1856, in execute
    if renpy.python.py_eval(condition):
  File "/home/armen/prog/renpy-8.3.7-sdk/renpy/python.py", line 1218, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/home/armen/prog/renpy-8.3.7-sdk/renpy/python.py", line 1211, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 358, in <module>
    if girl2_killed == False and girl2_geri == False:
NameError: name 'girl2_geri' is not defined

Linux-6.14.4-arch1-2-x86_64-with-glibc2.41 x86_64
Ren'Py 8.3.7.25031702
Armenian project 1.0
Sun May  4 11:58:39 2025
